# Learn more: https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "replace-with-your-shopify-client-id"
name = "Skuard"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = [ "products/create" ]
uri = "/webhooks/products/create"

[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "/webhooks/products/update"

[[webhooks.subscriptions]]
topics = [ "products/delete" ]
uri = "/webhooks/products/delete"
